title: "Mi Portfolio"
description: "Portfolio de desarrollo web"
baseurl: ""
url: "https://anthony-alarcon-castaneda.github.io"
theme: jekyll-theme-minimal
author: "Anthony Alarcón"
github_username: "AJPAC33"
plugins:
  - jekyll-feed
markdown: kramdown
exclude: ["node_modules", "vendor"]
